name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 23 for gradle
        uses: actions/setup-java@v2
        with:
          java-version: 23
          distribution: 'temurin'

      - name: Set up JDK 24 for project
        uses: actions/setup-java@v2
        with:
          java-version: 24
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build #-D org.gradle.java.home=
